docs/dfRestPrototype/README.md
=> Datafoundary APIs prototype

src/com/asiainfo/ocmanager/monitor/client/RestClient.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java
=> 修复重复创建二级租户失败及加强异常保护

WebContent/WEB-INF/conf/getKafakQuota.sh, src/com/asiainfo/ocmanager/dacp/model/DacpResult.java
=> resolve dacpResult

WebContent/WEB-INF/conf/server.properties, pom.xml, src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/security/SecurityManager.java, src/com/asiainfo/ocmanager/service/broker/plugin/KafkaResourcePeeker.java, src/com/asiainfo/ocmanager/service/client/KafkaClient.java, src/com/asiainfo/ocmanager/utils/HadoopConfiguration.java
=> kafka resource monitor added

WebContent/WEB-INF/conf/ldap.properties, WebContent/WEB-INF/conf/server.properties, src/com/asiainfo/ocmanager/auth/LdapWrapper.java, src/com/asiainfo/ocmanager/auth/utils/LdapUtils.java, src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/rest/resource/UserResource.java
=> 后台支持从LDAP获取用户列表

WebContent/WEB-INF/conf/ldap.properties, src/com/asiainfo/ocmanager/rest/resource/UserResource.java
=> 新增RestAPI获取Ldap用户列表

src/com/asiainfo/ocmanager/auth/LdapWrapper.java, src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/rest/constant/ResponseCodeConstant.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java, src/com/asiainfo/ocmanager/utils/ServerConfiguration.java
=> Add privilege control over tenant-relative operations

WebContent/WEB-INF/conf/server.properties, WebContent/WEB-INF/web.xml, src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/rest/listener/EnvInitializer.java, src/com/asiainfo/ocmanager/security/AuthScheduller.java, src/com/asiainfo/ocmanager/security/SecurityManager.java
在安全模式下的集群，需要RestServer对后台服务进行认证。
=> 增加Kerberos认证

src/com/asiainfo/ocmanager/persistence/mapper/ServiceInstanceMapper.java, src/com/asiainfo/ocmanager/persistence/mapper/ServiceInstanceMapper.xml, src/com/asiainfo/ocmanager/persistence/test/TestServiceInstance.java, src/com/asiainfo/ocmanager/rest/resource/KerberosResource.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java, src/com/asiainfo/ocmanager/rest/resource/persistence/ServiceInstancePersistenceWrapper.java
=> 修复不同服务下的实例资源名重复报错

src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java, src/com/asiainfo/ocmanager/rest/resource/utils/ServiceType.java, src/com/asiainfo/ocmanager/rest/resource/utils/TenantQuotaUtils.java
=> bsi扩容支持资源限制

src/com/asiainfo/ocmanager/concurrent/TenantLockerPool.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java, src/com/asiainfo/ocmanager/rest/resource/utils/TenantUtils.java
=> BSI加入多线程租户同步

src/com/asiainfo/ocmanager/concurrent/TenantLockerPool.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java
=> correct locker synchronization to parent locker when create/update

README.md, WebContent/WEB-INF/external/hosts_dummy, database/mysql/initOCManager.sql, pom.xml, src/com/asiainfo/ocmanager/rest/bean/service/instance/HiveServiceInstanceQuotaBean.java, src/com/asiainfo/ocmanager/rest/constant/ResponseCodeConstant.java, src/com/asiainfo/ocmanager/rest/resource/ExternalFileResource.java, src/com/asiainfo/ocmanager/rest/resource/QuotaResource.java, src/com/asiainfo/ocmanager/rest/resource/utils/ServiceType.java, src/com/asiainfo/ocmanager/service/broker/plugin/HiveResourcePeeker.java
=> 更新README新增下载hosts文件接口

README.md, WebContent/WEB-INF/conf/server.properties, src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/rest/resource/UserResource.java, src/com/asiainfo/ocmanager/service/client/RangerClient.java
新增用户时同步用户到ranger db， 解决ranger usersync 进程同步ldap周期过大导致的用户授权失败。
=> sync up user to ranger db when new user added into OCM

src/com/asiainfo/ocmanager/rest/resource/TenantResource.java
=> fix issue #308, forbid creating tenants which are parreled with root

src/com/asiainfo/ocmanager/rest/bean/service/instance/ServiceInstanceQuotaBean.java, src/com/asiainfo/ocmanager/utils/Catalog.java
=> QuotaBean支持接入多个同种服务类型的多个服务

WebContent/WEB-INF/conf/server.properties, WebContent/WEB-INF/conf/services.ini, src/com/asiainfo/ocmanager/service/broker/plugin/HbaseResourcePeeker.java, src/com/asiainfo/ocmanager/service/client/v2/HbaseClient.java, src/com/asiainfo/ocmanager/service/client/v2/KafkaClient.java
=> Kafka客户端配置文件精简

README.md, src/com/asiainfo/ocmanager/service/client/MailClient.java
=> update readme.md and all

WebContent/WEB-INF/conf/sso.properties, src/com/asiainfo/ocmanager/rest/constant/Constant.java, src/com/asiainfo/ocmanager/rest/filter/AsiainfoPrdSSOFilter.java, src/com/asiainfo/ocmanager/utils/SSOConfiguration.java
Add prd sso filter to support the sso with other apps
=> PRDBD_REQ_20180312_0021 CM rest support prd sso

src/com/asiainfo/ocmanager/utils/Catalog.java, src/com/asiainfo/ocmanager/utils/ClusterConfig.java, src/com/asiainfo/ocmanager/utils/ClustersIni.java, src/com/asiainfo/ocmanager/utils/MailServerProperties.java, src/com/asiainfo/ocmanager/utils/ServerConfiguration.java, src/com/asiainfo/ocmanager/utils/ServicesIni.java, src/com/asiainfo/ocmanager/utils/ShellCommandUtil.java, src/com/asiainfo/ocmanager/utils/TenantTree.java
1. format some code
2. remove the invalid main function
=> PRDBD_REQ_20180312_0021 rest code enhancement

src/com/asiainfo/ocmanager/persistence/mapper/TenantMapper.xml
the tenant lifecycle duetime also should be in create and update
=> PRDBD_REQ_20180311_0002 add duetime when create and update the tenant

src/com/asiainfo/ocmanager/utils/Catalog.java
log and performence enhancement
=>  PRDBD_BUG_20180503_0015

src/com/asiainfo/ocmanager/rest/bean/TenantQuotaBeanV2.java, src/com/asiainfo/ocmanager/rest/resource/utils/TenantQuotaUtils.java
1.change the long to double to support the float number
2.also the resource limitation can large than max long
=> PRDBD_REQ_20180312_0021 fix the more than max long resource limitation

src/com/asiainfo/ocmanager/rest/resource/utils/TenantUtils.java, src/com/asiainfo/ocmanager/utils/DateTimeUtil.java
format the date time passed from UI
=> PRDBD_REQ_20180311_0002 support set the tenant due time

src/com/asiainfo/ocmanager/rest/resource/executor/TenantResourceAssignRoleExecutor.java
=> PRDBD_REQ_20180311_000DBD_REQ_20180311_0002

src/com/asiainfo/ocmanager/rest/resource/TenantResource.java
log enhancement of deprovisionng bsi
=> PRDBD_BUG_20180518_0008

src/com/asiainfo/ocmanager/rest/bean/ServiceInstanceDefaultQuotaBean.java, src/com/asiainfo/ocmanager/rest/bean/service/instance/ElasticsearchServiceInstanceQuotaBean.java, src/com/asiainfo/ocmanager/rest/bean/service/instance/ServiceInstanceQuotaBean.java, src/com/asiainfo/ocmanager/rest/bean/service/instance/ServiceInstanceQuotaConst.java, src/com/asiainfo/ocmanager/rest/resource/utils/QuotaCommonUtils.java, src/com/asiainfo/ocmanager/utils/ServicesDefaultQuotaConf.java
=> PRDBD_BUG_20180517_0027 ElasticSearch资源限定未完成

src/com/asiainfo/ocmanager/rest/filter/AuthFilter.java
=> PRDBD_BUG_20180522_0031 hit 403 when login include /login/

src/com/asiainfo/ocmanager/auth/LdapWrapper.java, src/com/asiainfo/ocmanager/exception/OcmanagerRuntimeException.java
=> PRDBD_BUG_20180521_0028 Catch Exception instead of Throwable

src/com/asiainfo/ocmanager/concurrent/TenantLockerPool.java, src/com/asiainfo/ocmanager/exception/OcmanagerRuntimeException.java
=> PRDBD_BUG_20180521_0029 fix sonar issue

src/com/asiainfo/ocmanager/utils/KerberosConfiguration.java, src/com/asiainfo/ocmanager/utils/SSOConfiguration.java
=> PRDBD_BUG_20180518_0008 fix typo

src/com/asiainfo/ocmanager/persistence/model/Tenant.java, src/com/asiainfo/ocmanager/rest/bean/service/instance/RedisServiceInstanceQuotaBean.java, src/com/asiainfo/ocmanager/rest/resource/utils/TenantUtils.java, src/com/asiainfo/ocmanager/utils/DateTimeUtil.java, src/com/asiainfo/ocmanager/utils/TenantTree.java, src/com/asiainfo/ocmanager/utils/TenantTreeUtil.java
fix bugs PRDBD_BUG_20180605_0011,PRDBD_BUG_20180605_0012
=>  fix bugs PRDBD_BUG_20180605_0011,PRDBD_BUG_20180605_0012

WebContent/WEB-INF/web.xml, src/com/asiainfo/ocmanager/rest/filter/AuthFilter.java, src/com/asiainfo/ocmanager/rest/resource/AmbariResource.java, src/com/asiainfo/ocmanager/rest/resource/AuthcResource.java, src/com/asiainfo/ocmanager/rest/resource/ExternalFileResource.java, src/com/asiainfo/ocmanager/rest/resource/KerberosResource.java, src/com/asiainfo/ocmanager/rest/resource/QuotaResource.java, src/com/asiainfo/ocmanager/rest/resource/ServiceResource.java, src/com/asiainfo/ocmanager/rest/resource/TenantResource.java, src/com/asiainfo/ocmanager/rest/resource/UserResource.java, src/log4j.xml
=> audit log code by wangchen

docs/workflow/README.md, src/com/asiainfo/ocmanager/persistence/mapper/ApplyBillMapper.java, src/com/asiainfo/ocmanager/persistence/mapper/ApplyBillMapper.xml, src/com/asiainfo/ocmanager/persistence/model/ApplyBill.java, src/com/asiainfo/ocmanager/persistence/test/TestApplyBill.java, src/com/asiainfo/ocmanager/rest/resource/persistence/ApplyBillPersistenceWrapper.java, src/com/asiainfo/ocmanager/rest/resource/v2/ApplyBillResource.java, src/com/asiainfo/ocmanager/rest/resource/v2/CommonWorkflowResource.java, src/com/asiainfo/ocmanager/rest/resource/v2/ServiceInstanceWorkflowResource.java, src/com/asiainfo/ocmanager/rest/resource/workflow/bean/Assignee.java, src/com/asiainfo/ocmanager/rest/resource/workflow/bean/ProcessInstanceBean.java, src/com/asiainfo/ocmanager/rest/resource/workflow/bean/TaskBean.java, src/com/asiainfo/ocmanager/workflow/constant/Constant.java, src/com/asiainfo/ocmanager/workflow/process/Process.java, src/com/asiainfo/ocmanager/workflow/process/ServiceInstanceProcess.java, src/com/asiainfo/ocmanager/workflow/util/ActivitiConfiguration.java, src/com/asiainfo/ocmanager/workflow/util/MysqlConfiguration.java
=> add apply service instance workflow and bill

docs/cloudProvider/README.md
=> Init cloudprovider docs.
